### ISSUE TITLE
反连问题

### ISSUE THREAD

**Issue by HiIk-9527** [chushuai/wscan#16]
客户端配置
```
client:
    remote_server: true
    http_base_url: "http://1.1.1.1:1111"
    dns_server_ip: "1.1.1.1"
```

![image](https://github.com/chushuai/wscan/assets/69377487/f90a14fd-fff8-433a-a0ec-271d47915acf)

并且服务端访问并不需要登录就可进行操作

**Comment by chushuai** [comment]
能发下客户端完整的配置吗?

**Comment by HiIk-9527** [comment]
这边我是样例的
客户端:
```
reverse:
    db_file_path: "xx.db"
    token: "xxx"
    http:
        enabled: false
        listen_ip: 0.0.0.0
        listen_port: ""
        ip_header: ""
    dns:
        enabled: false
        listen_ip: 0.0.0.0
        domain: ""
        is_domain_name_server: false
        resolve:
            - type: A
              record: localhost
              value: 127.0.0.1
              ttl: 60
    client:
        remote_server: true
        http_base_url: "http://1.1.1.1:1111"
        dns_server_ip: "1.1.1.1"
```
服务端:
```
reverse:
    db_file_path: "xx.db"
    token: "xxx"
    http:
        enabled: true
        listen_ip: 0.0.0.0
        listen_port: "1111"
        ip_header: ""
    dns:
        enabled: true
        listen_ip: 0.0.0.0
        domain: "xx.xx"
        is_domain_name_server: true
        resolve:
            - type: A
              record: localhost
              value: 127.0.0.1
              ttl: 60
    client:
        remote_server: false
        http_base_url: ""
        dns_server_ip: ""
```
