### ISSUE TITLE
分享你的Wscan扫描测试经验！

### ISSUE THREAD

**Issue by chushuai** [chushuai/wscan#18]
最近在对Wscan进行优化，希望收集各种靶场使用 Wscan 扫描的测试报告。如果你曾经使用过 Wscan 进行扫描测试，无论是在实验室环境还是实际应用中，都非常欢迎你分享你的经验和结果。为保护隐私，请不要包含具体的 IP 地址、域名或其他敏感信息。

**Comment by Teicu** [comment]
<img width="976" alt="Screenshot 2024-07-08 at 08 46 51" src="https://github.com/chushuai/wscan/assets/1572822/bc1ac759-7cd6-4508-9a1a-ffd9e8b3bae0">
 

but https://github.com/chushuai/wscan-poc/releases does not exist. 404 

<img width="739" alt="Screenshot 2024-07-08 at 08 47 40" src="https://github.com/chushuai/wscan/assets/1572822/88439fdd-3501-47b7-927c-54585fc8f2d9">
<img width="799" alt="Screenshot 2024-07-08 at 08 47 27" src="https://github.com/chushuai/wscan/assets/1572822/0c6882f4-ab9b-4968-bbed-83fdfb507fa1">

**Comment by chushuai** [comment]
Wscan目前不提供漏扫插件，需要自行下载，做一些配置即可发挥nuclei、xray插件最大的作用
![image](https://github.com/chushuai/wscan/assets/5875458/bf3634a0-7d36-435d-8a1c-8530b779003e)

**Comment by Teicu** [comment]
so here the path with template should be added? 

<img width="716" alt="Screenshot 2024-07-08 at 14 52 45" src="https://github.com/chushuai/wscan/assets/1572822/18cca0d2-8293-4529-9b91-edf439d47a2a">

**Comment by Teicu** [comment]
please let me know if the configuration is correct, thank you 

<img width="606" alt="Screenshot 2024-07-08 at 15 02 53" src="https://github.com/chushuai/wscan/assets/1572822/2e6bc5b3-c183-4315-b207-630e584dea4a">

**Comment by chushuai** [comment]
Update the scanner to the latest version, refer to the following configuration

https://github.com/chushuai/wscan?tab=readme-ov-file#poc%E6%89%AB%E6%8F%8F
```
    prometheus:
        enabled: true
        depth: 1
        auto_load_poc: false
        include_poc: 
          - C:\wscan_windows_amd64.exe\wscan-poc\pocs
        exclude_poc: []
```
